open-ce/tensorflow-feedstock

buildscripts/set_tensorflow_nvidia_bazelrc.sh, recipe/meta.yaml
Fixes build failure on baremetal.
=> Fixed build on baremetal

recipe/meta.yaml
=> Fix the build string for libtensorflow

tests/open-ce-tests.yaml
Fixes https://github.com/open-ce/open-ce/issues/146
=> add TF tests

recipe/0304-Fixed-models-test-on-x86.patch, tests/open-ce-tests.yaml
=> Fixed TF tests

buildscripts/set_python_path_for_bazelrc.sh, buildscripts/set_tensorflow_bazelrc.sh, buildscripts/set_tensorflow_nvidia_bazelrc.sh, recipe/build-libtensorflow.sh, recipe/build-pip-package.sh, scripts/activate.sh, scripts/deactivate.sh, scripts/tensorflow-test, scripts/test-tensorflow-installation-r1.py, scripts/test-tensorflow-installation.py
Fixes https://github.com/open-ce/open-ce/issues/258.
=> Updated copyright information

meta_recipe/meta.yaml, recipe/0303-Eigen-customized.patch, recipe/meta.yaml
=> Updated to 2.4.1

tests/open-ce-tests.yaml
Fixes https://github.com/open-ce/open-ce/issues/301.
=> Fixed models repo version to match with TF 2.4.1

recipe/meta.yaml, recipe/open-ce-info.yaml
Add third party information that can be read by the `open-ce get licenses` tool. See https://github.com/open-ce/open-ce/pull/335.
=> Add Open-CE info file

recipe/meta.yaml, recipe/open-ce-info.yaml
Clean's up some of the license information for statically linked packages.
=> Update license info

buildscripts/set_tensorflow_bazelrc.sh, config/conda_build_config.yaml, recipe/meta.yaml
=> New mkl implementation

README.md, meta_recipe/meta.yaml, recipe/meta.yaml
Correcting URL addresses that are incorrect.
=> Corrections to invalid external URL addresses

recipe/0305-Updated-protobuf-to-3.11.2.patch, recipe/meta.yaml
Updated prootobuf to be used at build time by TF.
=> [1.2] Updated protobuf to 3.11.2

recipe/meta.yaml
This isn't elegant but pinning to the minimal at build time gives us what we want.
=> [1.2] pin sqlite to minimal at build time

tests/open-ce-tests.yaml
=> Added git in feedstock tests

config/conda_build_config.yaml, meta_recipe/meta.yaml, recipe/meta.yaml
Update to TF 2.4.2.
Needs GCC7.3 on ppc64le
Still needs some more testing. 
=> Update to 2.4.2

recipe/meta.yaml
Adds grpcio to the runtime dependency of TF.
=> Added grpcio as runtime dep of TF

recipe/build-pip-package.sh, recipe/meta.yaml
Reduces the number of jobs used during a build. Without this, builds on Power within containers are failing.
=> Reduce jobs

recipe/build-libtensorflow.sh, recipe/build-pip-package.sh, recipe/meta.yaml
Adjust libgcc and libstdc++ runtime dependencies for xgboost
open-ce/open-ce#452
Also cherry-picks https://github.com/open-ce/tensorflow-feedstock/commit/ead9cd570a86a812845ea27fb0244ca7a2e06c3b from main
=> [1.1,1.2]  Fix libgcc runtime

recipe/0305-Updated-protobuf-to-3.14.patch, recipe/meta.yaml
This updates the TF recipe to build with protobuf 3.14.
requires: https://github.com/open-ce/open-ce/pull/451
=> Update recipe for protobuf 3.14

buildscripts/set_tensorflow_nvidia_bazelrc.sh, recipe/meta.yaml
Disable TensorRT in OpenCE1.3 as it doesn't fit dependency-wise.
Will re-enable in 1.4 with TRT8.
=> Disable TensorRT for 1.3

recipe/0309-disable-ppc64le-custom-gemm_pack_rhs-to-use-the-convolution-specialization.patch, recipe/meta.yaml
PR #55 should have only been for cpu builds. The updated eigen version needs
some other commits from upstream to work on gpu builds so we'll just avoid it.
=> only add gemm pack opt for ppc64le cpu build

recipe/build-pip-package.sh, recipe/meta.yaml
Fixes bazel build flags so that it uses the resources as available from the system and with no hard-coded magic numbers.
https://github.com/open-ce/open-ce/issues/471
=> Changed build options of TF to work as per system configuration

config/build-config.yaml
Add required resources information for building tensorflow.
Note, the build number wasn't increased, since no change is made to the package.
=> Add resources

config/build-config.yaml
Add required resources information for building tensorflow.
Note, the build number wasn't increased, since no change is made to the package.
=> [1.1, 1.2] Add resources information

meta_recipe/meta.yaml, recipe/meta.yaml
=> Updated to TF 2.5.1 tag

meta_recipe/meta.yaml, recipe/meta.yaml
=> [1.1, 1.2] Update recipe to 2.4.3

buildscripts/set_tensorflow_nvidia_bazelrc.sh, recipe/meta.yaml
Use `cuda_levels_details` from https://github.com/open-ce/open-ce/blob/7cab6838cdec5c7aa7765750e5081405db27d8e9/envs/conda_build_config.yaml#L335-L339 to set compute capability. 
Requires -  https://github.com/open-ce/open-ce/pull/502
=> additional change for hw cap update

meta_recipe/meta.yaml, recipe/meta.yaml
=> Refresh TF to 2.6.2

recipe/meta.yaml
=> Updated to TF 2.4.4

meta_recipe/meta.yaml
TF Meta package version update
=> Updated version of TF meta package

recipe/0305-Updated-protobuf-version.patch, recipe/meta.yaml
=> Updated recipe for protobuf 3.19

recipe/build-pip-package.sh, recipe/meta.yaml
=> build with limited jobs and ram_resources

recipe/build-pip-package.sh, recipe/meta.yaml
=> [main] build with limited jobs and ram_resources (#77)

recipe/build-pip-package.sh, recipe/meta.yaml
=> [1.4] build with limited jobs and ram_resources (#77)

buildscripts/set_tensorflow_bazelrc.sh, meta_recipe/meta.yaml, recipe/0305-Updated-protobuf-version.patch, recipe/0307-Fix-for-eigen-TensorReduction.patch, recipe/0309-Build-llvm-for-ppc64le-target.patch, recipe/0310-Updated-Dist-info-for-tf-estimator-tensorboard-and-k.patch, recipe/0311-Support-ppc64le-in-cpuinfo-dependency.patch, recipe/0312-Fixed-URL-of-datasets.patch, recipe/meta.yaml, tests/open-ce-tests.yaml
=> 280 update

buildscripts/set_tensorflow_bazelrc.sh
- Fixed error `[: missing `]'` in line 30, line 45, line 54 and main syntax commonality
=> Fix bash script error in set_tensorflow_bazelrc

recipe/meta.yaml
=> removed PKG_HASH from build string

meta_recipe/meta.yaml, recipe/0310-Updated-Dist-info-for-tf-estimator-tensorboard-and-k.patch, recipe/meta.yaml
=> Refresh to TF 2.8.1

meta_recipe/meta.yaml, recipe/meta.yaml
=> Update to TF 2.7.2

recipe/build-pip-package.sh, recipe/meta.yaml
=> Fixed x86 py38 build

recipe/build-pip-package.sh
=> Fixed cuda 11.4 py38 build on x86

buildscripts/set_tensorflow_bazelrc.sh, recipe/build-pip-package.sh, recipe/meta.yaml
=> Use Redhat toolchain for Power10 builds

buildscripts/set_tensorflow_bazelrc.sh, recipe/meta.yaml, tests/open-ce-tests.yaml
=> Fixed s390x build and feedstock tests

recipe/meta.yaml
=> remove pin for sqlite

meta_recipe/meta.yaml, recipe/0313-lite-Switch-to-Flatbuffer-2.0.5.patch, recipe/meta.yaml
=> Updated to TF 2.9.2

meta_recipe/meta.yaml, recipe/meta.yaml
=> Updated to TF 2.9.3

recipe/0305-Updated-protobuf-version.patch, recipe/build-pip-package.sh, recipe/meta.yaml
=> Updated protobuf to 3.19.6

meta_recipe/meta.yaml, recipe/0202-Remove-extra-null-terminators.patch, recipe/0310-Updated-Dist-info-for-tf-estimator-tensorboard-and-k.patch, recipe/meta.yaml
=> 2.12 update

recipe/meta.yaml, recipe/patches/0101-CVE-2023-25672.patch, recipe/patches/0102-CVE-2023-25673_and_25674.patch, recipe/patches/0103-CVE-2023-25667.patch, recipe/patches/0104-CVE-2023-25671.patch, recipe/patches/0105-CVE-2023-27579.patch, recipe/patches/0106-CVE-2023-25669.patch, recipe/patches/0107-CVE-2023-25670.patch, recipe/patches/0108-CVE-2023-25663.patch, recipe/patches/0109-CVE-2023-25662.patch, recipe/patches/0110-CVE-2023-25660.patch, recipe/patches/0111-CVE-2023-25659.patch, recipe/patches/0112-CVE-2023-25666.patch, recipe/patches/0113-CVE-2023-25665.patch, recipe/patches/0114-CVE-2023-25675.patch, recipe/patches/0115-CVE-2023-25676.patch, recipe/patches/0116-CVE-2023-25801.patch
This PR includes patches of commits from upstream TF 2.12, that addresses several high priority CVEs.
=> Include fixes for CVES from upstream Tensorflow 2.12

recipe/meta.yaml
=> Disable jax for P10

recipe/meta.yaml, recipe/patches/0117-CVE-2023-25664.patch, recipe/patches/0118-CVE-2023-25661.patch
=> Back ported fixes for CVE-2023-25664 and CVE-2023-25661

recipe/build-pip-package.sh
=> [1.5] Call common function for bazel cleanup

recipe/meta.yaml
=> Remove wheel pin

recipe/0310-Updated-Dist-info-for-tf-estimator-tensorboard-and-k.patch, recipe/meta.yaml
=> Fixed pip check for TF IO on s390x

config/build-config.yaml
=> Reduce resources to 10GB for ppc

recipe/meta.yaml, recipe/patches/0001-Added-fix-for-a-vuln-in-printing-empty-tensors.patch
=> [1.7] Added patch to fix vulnerability in printing empty tensors

buildscripts/set_tensorflow_bazelrc.sh, recipe/build-pip-package.sh
Fixes the following errors:
```
In file included from /tmp/pip-wheel-m9urij4j/h5py_71841c546e65458497d7d416326df4df/h5py/defs.c:805:
/tmp/pip-wheel-m9urij4j/h5py_71841c546e65458497d7d416326df4df/h5py/api_compat.h:27:10: fatal error: hdf5.h: No such file or directory
27 | #include "hdf5.h"
|          ^~~~~~~~
compilation terminated.
error: command '/opt/rh/gcc-toolset-12/root/usr/bin/gcc' failed with exit code 1
```
```
/usr/include/bits/string_fortified.h:59:10: error: '__builtin_memset' may write between 16 and 2147483647 bytes into a region of size 15 [-Werror=stringop-overflow=]
59 |   return __builtin___memset_chk (__dest, __ch, __len,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
60 |                                  __glibc_objsize0 (__dest));
```
1. All tests and other …
=> fix build on P10

recipe/meta.yaml
=> Remove termcolor pin

recipe/meta.yaml
=> Relax termcolor

recipe/0327-Revert-Add-host-triple-option.-Previously-the-tool-w.patch, recipe/meta.yaml
The change from commit - https://github.com/tensorflow/tensorflow/commit/4bc5c7969b209193ffbc73591ead4f8ee6a6d5a3 caused build failure for PPC CUDA variant. So adding a patch to revert it. 
=> Fix Build for TF CUDA

buildscripts/set_tensorflow_bazelrc.sh, meta_recipe/meta.yaml, recipe/0001-Disabled-SYS_SYSCTL-for-P10.patch, recipe/0310-Updated-Dist-info-for-tf-estimator-tensorboard-and-k.patch, recipe/build-pip-package.sh, recipe/meta.yaml
=> [1.9.5] Updated TF to v2.13.1

recipe/meta.yaml
=> Added pip check to test section

recipe/build-pip-package.sh, recipe/meta.yaml
=> remove setuptools 68.* and 65.* files from the package

recipe/meta.yaml
=> pin to ml_dtypes and disabled pip chk as it needs dependencies
